using UnityEngine;

[CreateAssetMenu(fileName = "NewVoxelModel", menuName = "Voxel/Voxel Model")]
public class VoxelModelSO : ScriptableObject
{
    [Header("Data Source")]
    [Tooltip("Drag the .json file generated by the Scanner here.")]
    public TextAsset modelJson;

    // --- RUNTIME CACHE ---
    // We don't serialize this. We build it from the JSON at runtime.
    private Color32[] cachedVoxels;

    public Color32 GetVoxel(int x, int y, int z)
    {
        // 1. Lazy Load: If cache is empty, load it now
        if (cachedVoxels == null || cachedVoxels.Length != 512)
        {
            LoadModel();
        }

        // 2. Boundary Safety
        if (x < 0 || x >= 8 || y < 0 || y >= 8 || z < 0 || z >= 8)
            return new Color32(0, 0, 0, 0);

        return cachedVoxels[x + (y * 8) + (z * 64)];
    }

    private void LoadModel()
    {
        // Default to empty if no file is assigned
        if (modelJson == null)
        {
            cachedVoxels = new Color32[512];
            return;
        }

        // Parse JSON
        MicroModelData data = JsonUtility.FromJson<MicroModelData>(modelJson.text);

        // Validate Data
        if (data != null && data.voxels != null && data.voxels.Length == 512)
        {
            cachedVoxels = data.voxels;
        }
        else
        {
            Debug.LogError($"[VoxelModelSO] Failed to load JSON in {name}. Data might be corrupt or old version.");
            cachedVoxels = new Color32[512];
        }
    }
}

// --- JSON CONTAINER CLASS ---
// This defines the structure of the file we save/load
[System.Serializable]
public class MicroModelData
{
    public Color32[] voxels = new Color32[512];
}